### ISSUE TITLE
readme should mention import re problem 

### ISSUE THREAD

**Issue by stleary** [marilynel/software_engineering_prj#1]
Some installations have to manually import the re library in order to run marine_taxo.py. This should be called out in the readme.

**Comment by marilynel** [comment]
Hopefully fixed, lmk if it could be said in a better way

**Comment by stleary** [comment]
Try adding an additional line between the end of the list and the 're' sentence. Otherwise, it will be displayed on the same line. Just the way the markdown renderer works.
